### PR TITLE
Option to keep parameters reference in `ExponentialMovingAverage`

### PR DESCRIPTION
**Pull request by Linux-cpp-lisp**
(This PR is a branch off of the `tests` branch in #4 to allow it to be considered separately, since it's a more subjective change. If you choose to merge this PR, it should probably be merged after #4.)

One inconvenience in using this library is the need to pass `model.parameters()` in at every call, unlike, for example, a PyTorch optimizer, which keeps track of the parameters it was initialized with. This PR makes the `parameters` argument to the various methods optional, in which case the parameters with which the `ExponentialMovingAverage` was initialized with will be used.

To maintain the original garbage collection behavior of this library, I used `weakref` for storing the reference to the parameters. As a result, this PR shouldn't, as far as I can tell, affect users of the library even if they do complex things (like initializing with one models parameters, eventually throwing away that model, and then continuing to update or store to other models).

### CODE REVIEW

**Comment by fadel** [comment]
I like the idea. Keeping backwards compatibility is also great. Thanks!

**Comment by fadel** [comment]
I noticed you also updated the README accordingly. Do you mind opening a new pull request with it or may I copy from yours?

**Comment by Linux-cpp-lisp** [comment]
Thanks @fadel!

I can open a new pull request with the README, since I also made/am making one other addition (`state_dict` support and `.to(device)` support), if that makes sense to you?

**Comment by fadel** [comment]
Sounds good to me! Please go ahead.

**Comment by Linux-cpp-lisp** [comment]
@fadel I had some difficulty rebasing, so I went ahead and made a standalone PR for `state_dict` (code I already had) in #6. I'll fix the README in one more PR along with `.to` after making a fresh branch off of `master` with #6 merged into it to avoid more rebasing issues.

**Comment by fadel** [comment]
Thanks @Linux-cpp-lisp! Those issues are my fault, I squashed your commits into a single one and then merged. I only found out you built on top of them later, sorry,

**Comment by Linux-cpp-lisp** [comment]
@fadel I've filed a PR (#8 ) that includes updates to README with this as well as documenting some other new features :smiley:

**Pull request merged**
